/*
 * generated by Xtext
 */
package ro.ubbcluj.cs.ealf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.model.IResourceForEditorInputFactory;
import org.eclipse.xtext.ui.editor.model.XtextDocumentProvider;

import ro.ubbcluj.cs.ealf.ui.extra.EAlfCrossReferenceSerializer;
import ro.ubbcluj.cs.ealf.ui.extra.EAlfResourceForIEditorInputFactory;
import ro.ubbcluj.cs.ealf.ui.extra.EAlfXtextDocumentProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EAlfUiModule extends ro.ubbcluj.cs.ealf.ui.AbstractEAlfUiModule {
	public EAlfUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	// contributed by ro.ubbcluj.cs.ealf.ui.extra.EAlfXtextDocumentProvider
	public Class<? extends XtextDocumentProvider> bindDocumentProvider() {
		return EAlfXtextDocumentProvider.class;
	}

	// contributed by
	// ro.ubbcluj.cs.ealf.ui.extra.EAlfResourceForIEditorInputFactory
	public Class<? extends IResourceForEditorInputFactory> bindIResourceForEditorInputFactory() {
		return EAlfResourceForIEditorInputFactory.class;
	}

	// contributed by ro.ubbcluj.cs.ealf.ui.extra.EAlfCrossReferenceSerializer
	public Class<? extends org.eclipse.xtext.parsetree.reconstr.ITokenSerializer.ICrossReferenceSerializer> bindICrossReferenceSerializer() {
		return EAlfCrossReferenceSerializer.class;
	}

}
