/*
* generated by Xtext
*/
package ro.ubbcluj.cs.ealf.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class EAlfTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
