/*
 * generated by Xtext
 */
package ro.ubbcluj.cs.ealf;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EAlfRuntimeModule extends ro.ubbcluj.cs.ealf.AbstractEAlfRuntimeModule {

}
