/*
 * generated by Xtext
 */
package ro.ubbcluj.cs.ealf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EAlfUiModule extends ro.ubbcluj.cs.ealf.ui.AbstractEAlfUiModule {
	public EAlfUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
