
/*
 * generated by Xtext
 */
package ro.ubbcluj.cs.ealf.ui.internal;

import org.apache.log4j.Logger;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.osgi.framework.BundleContext;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.util.Modules;

import java.util.Map;
import java.util.HashMap;

/**
 * Generated
 */
public class EAlfActivator extends AbstractUIPlugin {

	private Map<String,Injector> injectors = new HashMap<String,Injector>();
	private static EAlfActivator INSTANCE;

	public Injector getInjector(String languageName) {
		return injectors.get(languageName);
	}
	
	@Override
	public void start(BundleContext context) throws Exception {
		super.start(context);
		INSTANCE = this;
		try {
			
			injectors.put("ro.ubbcluj.cs.ealf.EAlf", Guice.createInjector(
				Modules.override(Modules.override(getRuntimeModule("ro.ubbcluj.cs.ealf.EAlf")).with(getUiModule("ro.ubbcluj.cs.ealf.EAlf"))).with(getSharedStateModule())
			));
			
		} catch (Exception e) {
			Logger.getLogger(getClass()).error(e.getMessage(), e);
			throw e;
		}
	}
	
	public static EAlfActivator getInstance() {
		return INSTANCE;
	}
	
	protected Module getRuntimeModule(String grammar) {
		
		if ("ro.ubbcluj.cs.ealf.EAlf".equals(grammar)) {
		  return new ro.ubbcluj.cs.ealf.EAlfRuntimeModule();
		}
		
		throw new IllegalArgumentException(grammar);
	}
	protected Module getUiModule(String grammar) {
		
		if ("ro.ubbcluj.cs.ealf.EAlf".equals(grammar)) {
		  return new ro.ubbcluj.cs.ealf.ui.EAlfUiModule(this);
		}
		
		throw new IllegalArgumentException(grammar);
	}
	
	protected Module getSharedStateModule() {
		return new org.eclipse.xtext.ui.shared.SharedStateModule();
	}
	
}
