
/*
 * generated by Xtext
 */
 
package ro.ubbcluj.cs.ealf.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class EAlfExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ro.ubbcluj.cs.ealf.ui.internal.EAlfActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ro.ubbcluj.cs.ealf.ui.internal.EAlfActivator.getInstance().getInjector("ro.ubbcluj.cs.ealf.EAlf");
	}
	
}
